### ISSUE TITLE
Team Content export inconsistencies

### ISSUE THREAD

**Issue by stonecutter908** [dropbox/DropboxBusinessAdminTool#11]
From the Team Content tab, I am getting inconsistent results.  Sometimes the delta  between two runs of the report is as high as 100k+ files and folders.  I believe that the issue has to do with error(s) encountered during the calls to the files/list_folder_continue API.  Maybe a loop that would catch a failed API call (possibly to due to a temporary network condition) would do the trick?  It seems the app just keeps pushing processing forward.  Great tool that has saved me hours of API coding to get some content reports.

**Comment by jackb-dropbox** [comment]
Thanks! This has been fixed (continuation issue) in build 4.7 going out today.
