### ISSUE TITLE
Team Content report inconsistencies

### ISSUE THREAD

**Issue by stonecutter908** [dropbox/DropboxBusinessAdminTool#21]
Re-opening old issue:

From the Team Content tab, I am getting inconsistent results. Sometimes the delta between two runs of the report is as high as 100k+ files and folders. I believe that the issue has to do with error(s) encountered during the calls to the files/list_folder_continue API. Maybe a loop that would catch a failed API call (possibly to due to a temporary network condition) would do the trick? It seems the app just keeps pushing processing forward. Great tool that has saved me hours of API coding to get some content reports.

I'm still seeing the same inconsistencies noted above at version 5.1.1.  Back to back runs will very greatly in the number of total objects in the report.  And then if I zero in on a given folder where I know the exact properties of, the report will be much lower.

How can the tool be updated to improve reporting accuracy so the results can be trusted?

**Comment by jackb-dropbox** [comment]
There was an issue sometime back but was fixed and haven't seen any issues. Will look into it immediately!

**Comment by jackb-dropbox** [comment]
Just an update... I have definately found a couple things that are causing this and working on finishing it and testing. Will update you when complete and possibly to test if you would.
